// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package dao

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const linkEngagementDeliberations = `-- name: LinkEngagementDeliberations :batchexec
INSERT INTO app.engagement_deliberations (
    engagement_id,
    deliberation_id
) VALUES (
    $1,
    $2
)
ON CONFLICT DO NOTHING
`

type LinkEngagementDeliberationsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type LinkEngagementDeliberationsParams struct {
	EngagementID   uuid.UUID
	DeliberationID uuid.UUID
}

func (q *Queries) LinkEngagementDeliberations(ctx context.Context, arg []LinkEngagementDeliberationsParams) *LinkEngagementDeliberationsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.EngagementID,
			a.DeliberationID,
		}
		batch.Queue(linkEngagementDeliberations, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &LinkEngagementDeliberationsBatchResults{br, len(arg), false}
}

func (b *LinkEngagementDeliberationsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *LinkEngagementDeliberationsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const linkEngagementObservations = `-- name: LinkEngagementObservations :batchexec
INSERT INTO app.engagement_indicateur_observations (
    engagement_id,
    observation_id
) VALUES (
    $1,
    $2
)
ON CONFLICT DO NOTHING
`

type LinkEngagementObservationsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type LinkEngagementObservationsParams struct {
	EngagementID  uuid.UUID
	ObservationID uuid.UUID
}

func (q *Queries) LinkEngagementObservations(ctx context.Context, arg []LinkEngagementObservationsParams) *LinkEngagementObservationsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.EngagementID,
			a.ObservationID,
		}
		batch.Queue(linkEngagementObservations, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &LinkEngagementObservationsBatchResults{br, len(arg), false}
}

func (b *LinkEngagementObservationsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *LinkEngagementObservationsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertDeliberations = `-- name: UpsertDeliberations :batchexec
INSERT INTO app.deliberations (
    delib_id,
    collectivite,
    instance,
    coll_nom,
    coll_siret,
    delib_date,
    delib_objet,
    delib_matiere_code,
    delib_matiere_nom,
    pref_id,
    pref_date,
    vote_effectif,
    vote_reel,
    vote_pour,
    vote_contre,
    vote_abstention,
    raw_data
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17
)
ON CONFLICT (delib_id, collectivite, instance) DO UPDATE SET
    instance           = EXCLUDED.instance,
    coll_nom           = EXCLUDED.coll_nom,
    coll_siret         = EXCLUDED.coll_siret,
    delib_date         = EXCLUDED.delib_date,
    delib_objet        = EXCLUDED.delib_objet,
    delib_matiere_code = EXCLUDED.delib_matiere_code,
    delib_matiere_nom  = EXCLUDED.delib_matiere_nom,
    pref_id            = EXCLUDED.pref_id,
    pref_date          = EXCLUDED.pref_date,
    vote_effectif      = EXCLUDED.vote_effectif,
    vote_reel          = EXCLUDED.vote_reel,
    vote_pour          = EXCLUDED.vote_pour,
    vote_contre        = EXCLUDED.vote_contre,
    vote_abstention    = EXCLUDED.vote_abstention,
    raw_data           = EXCLUDED.raw_data
`

type UpsertDeliberationsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertDeliberationsParams struct {
	DelibID          string
	Collectivite     string
	Instance         string
	CollNom          string
	CollSiret        string
	DelibDate        time.Time
	DelibObjet       string
	DelibMatiereCode string
	DelibMatiereNom  string
	PrefID           *string
	PrefDate         *time.Time
	VoteEffectif     int32
	VoteReel         int32
	VotePour         int32
	VoteContre       int32
	VoteAbstention   int32
	RawData          []byte
}

func (q *Queries) UpsertDeliberations(ctx context.Context, arg []UpsertDeliberationsParams) *UpsertDeliberationsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.DelibID,
			a.Collectivite,
			a.Instance,
			a.CollNom,
			a.CollSiret,
			a.DelibDate,
			a.DelibObjet,
			a.DelibMatiereCode,
			a.DelibMatiereNom,
			a.PrefID,
			a.PrefDate,
			a.VoteEffectif,
			a.VoteReel,
			a.VotePour,
			a.VoteContre,
			a.VoteAbstention,
			a.RawData,
		}
		batch.Queue(upsertDeliberations, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertDeliberationsBatchResults{br, len(arg), false}
}

func (b *UpsertDeliberationsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertDeliberationsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertIndicateurObservations = `-- name: UpsertIndicateurObservations :batchexec
INSERT INTO app.indicateur_observations (
    key,
    reference,
    data
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (key, reference) DO UPDATE SET
    data       = EXCLUDED.data
`

type UpsertIndicateurObservationsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertIndicateurObservationsParams struct {
	Key       string
	Reference string
	Data      []byte
}

func (q *Queries) UpsertIndicateurObservations(ctx context.Context, arg []UpsertIndicateurObservationsParams) *UpsertIndicateurObservationsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Key,
			a.Reference,
			a.Data,
		}
		batch.Queue(upsertIndicateurObservations, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertIndicateurObservationsBatchResults{br, len(arg), false}
}

func (b *UpsertIndicateurObservationsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertIndicateurObservationsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
