// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deliberations.sql

package dao

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findDeliberationByID = `-- name: FindDeliberationByID :one
SELECT 
    id, delib_id, documents,
    collectivite, instance, 
    coll_nom, coll_siret, 
    delib_date, delib_objet, delib_matiere_code, delib_matiere_nom, 
    pref_id, pref_date, 
    vote_effectif, vote_reel, vote_pour, vote_contre, vote_abstention,
    created_at, updated_at 
FROM app.deliberations
WHERE id = $1
`

type FindDeliberationByIDRow struct {
	ID               uuid.UUID
	DelibID          string
	Documents        []byte
	Collectivite     string
	Instance         string
	CollNom          string
	CollSiret        string
	DelibDate        time.Time
	DelibObjet       string
	DelibMatiereCode string
	DelibMatiereNom  string
	PrefID           *string
	PrefDate         *time.Time
	VoteEffectif     int32
	VoteReel         int32
	VotePour         int32
	VoteContre       int32
	VoteAbstention   int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) FindDeliberationByID(ctx context.Context, id uuid.UUID) (FindDeliberationByIDRow, error) {
	row := q.db.QueryRow(ctx, findDeliberationByID, id)
	var i FindDeliberationByIDRow
	err := row.Scan(
		&i.ID,
		&i.DelibID,
		&i.Documents,
		&i.Collectivite,
		&i.Instance,
		&i.CollNom,
		&i.CollSiret,
		&i.DelibDate,
		&i.DelibObjet,
		&i.DelibMatiereCode,
		&i.DelibMatiereNom,
		&i.PrefID,
		&i.PrefDate,
		&i.VoteEffectif,
		&i.VoteReel,
		&i.VotePour,
		&i.VoteContre,
		&i.VoteAbstention,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeliberations = `-- name: ListDeliberations :many
SELECT 
    id, delib_id, 
    collectivite, instance, 
    coll_nom, coll_siret, 
    delib_date, delib_objet, delib_matiere_code, delib_matiere_nom, 
    pref_id, pref_date, 
    vote_effectif, vote_reel, vote_pour, vote_contre, vote_abstention, 
    created_at, updated_at 
FROM app.deliberations
WHERE
    -- Filtres optionnels : array vide ou NULL = pas de filtre
    ($1::text[] IS NULL 
        OR collectivite = ANY($1::text[]))
    AND ($2::text[] IS NULL 
        OR instance = ANY($2::text[]))
    AND ($3::text[] IS NULL 
        OR delib_matiere_code = ANY($3::text[]))
    AND ($4::date IS NULL 
        OR delib_date >= $4::date)
    AND ($5::date IS NULL 
        OR delib_date <= $5::date)
    AND ($6::text IS NULL 
        OR to_tsvector('french_unaccent', delib_objet) 
           @@ websearch_to_tsquery('french_unaccent', $6::text))
ORDER BY
    CASE WHEN $7::bool THEN delib_date END ASC,
    CASE WHEN NOT $7::bool THEN delib_date END DESC,
    id  -- tie-breaker pour stabilité
LIMIT $9
OFFSET $8
`

type ListDeliberationsParams struct {
	Collectivites []string
	Instances     []string
	Matieres      []string
	DateFrom      *time.Time
	DateTo        *time.Time
	Search        *string
	SortAsc       bool
	Offset        int32
	Limit         int32
}

type ListDeliberationsRow struct {
	ID               uuid.UUID
	DelibID          string
	Collectivite     string
	Instance         string
	CollNom          string
	CollSiret        string
	DelibDate        time.Time
	DelibObjet       string
	DelibMatiereCode string
	DelibMatiereNom  string
	PrefID           *string
	PrefDate         *time.Time
	VoteEffectif     int32
	VoteReel         int32
	VotePour         int32
	VoteContre       int32
	VoteAbstention   int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) ListDeliberations(ctx context.Context, arg ListDeliberationsParams) ([]ListDeliberationsRow, error) {
	rows, err := q.db.Query(ctx, listDeliberations,
		arg.Collectivites,
		arg.Instances,
		arg.Matieres,
		arg.DateFrom,
		arg.DateTo,
		arg.Search,
		arg.SortAsc,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeliberationsRow
	for rows.Next() {
		var i ListDeliberationsRow
		if err := rows.Scan(
			&i.ID,
			&i.DelibID,
			&i.Collectivite,
			&i.Instance,
			&i.CollNom,
			&i.CollSiret,
			&i.DelibDate,
			&i.DelibObjet,
			&i.DelibMatiereCode,
			&i.DelibMatiereNom,
			&i.PrefID,
			&i.PrefDate,
			&i.VoteEffectif,
			&i.VoteReel,
			&i.VotePour,
			&i.VoteContre,
			&i.VoteAbstention,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliberationsWithoutDocuments = `-- name: ListDeliberationsWithoutDocuments :many
SELECT id, delib_id, instance
FROM app.deliberations
WHERE documents IS NULL
ORDER BY delib_date DESC
LIMIT $1
`

type ListDeliberationsWithoutDocumentsRow struct {
	ID       uuid.UUID
	DelibID  string
	Instance string
}

func (q *Queries) ListDeliberationsWithoutDocuments(ctx context.Context, limit int32) ([]ListDeliberationsWithoutDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listDeliberationsWithoutDocuments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeliberationsWithoutDocumentsRow
	for rows.Next() {
		var i ListDeliberationsWithoutDocumentsRow
		if err := rows.Scan(&i.ID, &i.DelibID, &i.Instance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeliberationDocuments = `-- name: SetDeliberationDocuments :exec
UPDATE app.deliberations
SET documents = $1
WHERE id = $2
  AND documents IS NULL
`

type SetDeliberationDocumentsParams struct {
	Documents []byte
	ID        uuid.UUID
}

func (q *Queries) SetDeliberationDocuments(ctx context.Context, arg SetDeliberationDocumentsParams) error {
	_, err := q.db.Exec(ctx, setDeliberationDocuments, arg.Documents, arg.ID)
	return err
}
