// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: engagements.sql

package dao

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEngagement = `-- name: CreateEngagement :one
INSERT INTO app.engagements (
    title,
    content,
    created_by
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, title, content, created_by, created_at, updated_at
`

type CreateEngagementParams struct {
	Title     string
	Content   string
	CreatedBy uuid.UUID
}

func (q *Queries) CreateEngagement(ctx context.Context, arg CreateEngagementParams) (AppEngagement, error) {
	row := q.db.QueryRow(ctx, createEngagement, arg.Title, arg.Content, arg.CreatedBy)
	var i AppEngagement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findEngagementByID = `-- name: FindEngagementByID :one
SELECT
    e.id, e.title, e.content,
    e.created_by, u.email AS author_email,
    e.created_at, e.updated_at
FROM app.engagements e
JOIN app.users u ON u.id = e.created_by
WHERE e.id = $1
`

type FindEngagementByIDRow struct {
	ID          uuid.UUID
	Title       string
	Content     string
	CreatedBy   uuid.UUID
	AuthorEmail string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) FindEngagementByID(ctx context.Context, id uuid.UUID) (FindEngagementByIDRow, error) {
	row := q.db.QueryRow(ctx, findEngagementByID, id)
	var i FindEngagementByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedBy,
		&i.AuthorEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEngagementDeliberations = `-- name: ListEngagementDeliberations :many
SELECT
    d.id, d.delib_id,
    d.collectivite, d.instance,
    d.coll_nom, d.coll_siret,
    d.delib_date, d.delib_objet, d.delib_matiere_code, d.delib_matiere_nom,
    d.pref_id, d.pref_date,
    d.vote_effectif, d.vote_reel, d.vote_pour, d.vote_contre, d.vote_abstention,
    d.created_at, d.updated_at
FROM app.engagement_deliberations ed
JOIN app.deliberations d ON d.id = ed.deliberation_id
WHERE ed.engagement_id = $1
ORDER BY d.delib_date DESC, d.id
`

type ListEngagementDeliberationsRow struct {
	ID               uuid.UUID
	DelibID          string
	Collectivite     string
	Instance         string
	CollNom          string
	CollSiret        string
	DelibDate        time.Time
	DelibObjet       string
	DelibMatiereCode string
	DelibMatiereNom  string
	PrefID           *string
	PrefDate         *time.Time
	VoteEffectif     int32
	VoteReel         int32
	VotePour         int32
	VoteContre       int32
	VoteAbstention   int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) ListEngagementDeliberations(ctx context.Context, engagementID uuid.UUID) ([]ListEngagementDeliberationsRow, error) {
	rows, err := q.db.Query(ctx, listEngagementDeliberations, engagementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEngagementDeliberationsRow
	for rows.Next() {
		var i ListEngagementDeliberationsRow
		if err := rows.Scan(
			&i.ID,
			&i.DelibID,
			&i.Collectivite,
			&i.Instance,
			&i.CollNom,
			&i.CollSiret,
			&i.DelibDate,
			&i.DelibObjet,
			&i.DelibMatiereCode,
			&i.DelibMatiereNom,
			&i.PrefID,
			&i.PrefDate,
			&i.VoteEffectif,
			&i.VoteReel,
			&i.VotePour,
			&i.VoteContre,
			&i.VoteAbstention,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEngagementObservations = `-- name: ListEngagementObservations :many
SELECT o.id, o.key, o.reference, o.data, o.created_at, o.updated_at
FROM app.engagement_indicateur_observations eio
JOIN app.indicateur_observations o ON o.id = eio.observation_id
WHERE eio.engagement_id = $1
ORDER BY o.key, o.reference ASC
`

func (q *Queries) ListEngagementObservations(ctx context.Context, engagementID uuid.UUID) ([]AppIndicateurObservation, error) {
	rows, err := q.db.Query(ctx, listEngagementObservations, engagementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppIndicateurObservation
	for rows.Next() {
		var i AppIndicateurObservation
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Reference,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEngagements = `-- name: ListEngagements :many
SELECT
    e.id, e.title, e.content,
    e.created_by, u.email AS author_email,
    e.created_at, e.updated_at
FROM app.engagements e
JOIN app.users u ON u.id = e.created_by
ORDER BY e.created_at DESC, e.id
LIMIT $2
OFFSET $1
`

type ListEngagementsParams struct {
	Offset int32
	Limit  int32
}

type ListEngagementsRow struct {
	ID          uuid.UUID
	Title       string
	Content     string
	CreatedBy   uuid.UUID
	AuthorEmail string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListEngagements(ctx context.Context, arg ListEngagementsParams) ([]ListEngagementsRow, error) {
	rows, err := q.db.Query(ctx, listEngagements, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEngagementsRow
	for rows.Next() {
		var i ListEngagementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedBy,
			&i.AuthorEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
