// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: engagements.sql

package dao

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEngagement = `-- name: CreateEngagement :one
INSERT INTO app.engagements (
    title,
    reference,
    created_by
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, title, reference, created_by, created_at, updated_at
`

type CreateEngagementParams struct {
	Title     string
	Reference string
	CreatedBy uuid.UUID
}

func (q *Queries) CreateEngagement(ctx context.Context, arg CreateEngagementParams) (AppEngagement, error) {
	row := q.db.QueryRow(ctx, createEngagement, arg.Title, arg.Reference, arg.CreatedBy)
	var i AppEngagement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Reference,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEngagementUpdate = `-- name: CreateEngagementUpdate :one
INSERT INTO app.engagement_updates (
    engagement_id,
    status,
    content,
    event_date,
    deliberation_id,
    external_source,
    created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, engagement_id, status, content, event_date, deliberation_id, external_source,
    created_by, created_at, updated_at
`

type CreateEngagementUpdateParams struct {
	EngagementID   uuid.UUID
	Status         string
	Content        string
	EventDate      time.Time
	DeliberationID *uuid.UUID
	ExternalSource *string
	CreatedBy      uuid.UUID
}

func (q *Queries) CreateEngagementUpdate(ctx context.Context, arg CreateEngagementUpdateParams) (AppEngagementUpdate, error) {
	row := q.db.QueryRow(ctx, createEngagementUpdate,
		arg.EngagementID,
		arg.Status,
		arg.Content,
		arg.EventDate,
		arg.DeliberationID,
		arg.ExternalSource,
		arg.CreatedBy,
	)
	var i AppEngagementUpdate
	err := row.Scan(
		&i.ID,
		&i.EngagementID,
		&i.Status,
		&i.Content,
		&i.EventDate,
		&i.DeliberationID,
		&i.ExternalSource,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findEngagementByID = `-- name: FindEngagementByID :one
SELECT
    e.id, e.title, e.reference,
    e.created_by, u.email AS author_email,
    e.created_at, e.updated_at,
    COALESCE(latest.status, 'en_attente') AS status,
    (SELECT MAX(eu.event_date)
        FROM app.engagement_updates eu
        WHERE eu.engagement_id = e.id) AS latest_event_date
FROM app.engagements e
JOIN app.users u ON u.id = e.created_by
LEFT JOIN LATERAL (
    SELECT eu.status
    FROM app.engagement_updates eu
    WHERE eu.engagement_id = e.id
    ORDER BY eu.event_date DESC, eu.id DESC
    LIMIT 1
) latest ON TRUE
WHERE e.id = $1
`

type FindEngagementByIDRow struct {
	ID              uuid.UUID
	Title           string
	Reference       string
	CreatedBy       uuid.UUID
	AuthorEmail     string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Status          string
	LatestEventDate interface{}
}

func (q *Queries) FindEngagementByID(ctx context.Context, id uuid.UUID) (FindEngagementByIDRow, error) {
	row := q.db.QueryRow(ctx, findEngagementByID, id)
	var i FindEngagementByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Reference,
		&i.CreatedBy,
		&i.AuthorEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.LatestEventDate,
	)
	return i, err
}

const findEngagementUpdateByID = `-- name: FindEngagementUpdateByID :one
SELECT id, engagement_id, status, content, event_date, deliberation_id,
    external_source, created_by, created_at, updated_at
FROM app.engagement_updates
WHERE id = $1
`

func (q *Queries) FindEngagementUpdateByID(ctx context.Context, id uuid.UUID) (AppEngagementUpdate, error) {
	row := q.db.QueryRow(ctx, findEngagementUpdateByID, id)
	var i AppEngagementUpdate
	err := row.Scan(
		&i.ID,
		&i.EngagementID,
		&i.Status,
		&i.Content,
		&i.EventDate,
		&i.DeliberationID,
		&i.ExternalSource,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEngagementUpdates = `-- name: ListEngagementUpdates :many
SELECT
    eu.id, eu.status, eu.content, eu.event_date, eu.external_source, eu.deliberation_id,
    eu.created_by, u.email AS author_email, eu.created_at
FROM app.engagement_updates eu
JOIN app.users u ON u.id = eu.created_by
WHERE eu.engagement_id = $1
ORDER BY eu.created_at DESC, eu.id DESC
`

type ListEngagementUpdatesRow struct {
	ID             uuid.UUID
	Status         string
	Content        string
	EventDate      time.Time
	ExternalSource *string
	DeliberationID *uuid.UUID
	CreatedBy      uuid.UUID
	AuthorEmail    string
	CreatedAt      time.Time
}

func (q *Queries) ListEngagementUpdates(ctx context.Context, engagementID uuid.UUID) ([]ListEngagementUpdatesRow, error) {
	rows, err := q.db.Query(ctx, listEngagementUpdates, engagementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEngagementUpdatesRow
	for rows.Next() {
		var i ListEngagementUpdatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Content,
			&i.EventDate,
			&i.ExternalSource,
			&i.DeliberationID,
			&i.CreatedBy,
			&i.AuthorEmail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEngagements = `-- name: ListEngagements :many
SELECT
    e.id, e.title, e.reference,
    e.created_by, u.email AS author_email,
    e.created_at, e.updated_at,
    COALESCE(latest.status, 'en_attente') AS status,
    (SELECT MAX(eu.event_date)
        FROM app.engagement_updates eu
        WHERE eu.engagement_id = e.id) AS latest_event_date
FROM app.engagements e
JOIN app.users u ON u.id = e.created_by
LEFT JOIN LATERAL (
    SELECT eu.status
    FROM app.engagement_updates eu
    WHERE eu.engagement_id = e.id
    ORDER BY eu.event_date DESC, eu.id DESC
    LIMIT 1
) latest ON TRUE
ORDER BY e.created_at DESC, e.id
LIMIT $2
OFFSET $1
`

type ListEngagementsParams struct {
	Offset int32
	Limit  int32
}

type ListEngagementsRow struct {
	ID              uuid.UUID
	Title           string
	Reference       string
	CreatedBy       uuid.UUID
	AuthorEmail     string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Status          string
	LatestEventDate interface{}
}

func (q *Queries) ListEngagements(ctx context.Context, arg ListEngagementsParams) ([]ListEngagementsRow, error) {
	rows, err := q.db.Query(ctx, listEngagements, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEngagementsRow
	for rows.Next() {
		var i ListEngagementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Reference,
			&i.CreatedBy,
			&i.AuthorEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.LatestEventDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEngagement = `-- name: UpdateEngagement :one
UPDATE app.engagements
SET title = $1,
    reference = $2
WHERE id = $3
RETURNING id, title, reference, created_by, created_at, updated_at
`

type UpdateEngagementParams struct {
	Title     string
	Reference string
	ID        uuid.UUID
}

func (q *Queries) UpdateEngagement(ctx context.Context, arg UpdateEngagementParams) (AppEngagement, error) {
	row := q.db.QueryRow(ctx, updateEngagement, arg.Title, arg.Reference, arg.ID)
	var i AppEngagement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Reference,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEngagementUpdate = `-- name: UpdateEngagementUpdate :one
UPDATE app.engagement_updates
SET status = $1,
    content = $2,
    event_date = $3,
    deliberation_id = $4,
    external_source = $5
WHERE id = $6
RETURNING id, engagement_id, status, content, event_date, deliberation_id, external_source,
    created_by, created_at, updated_at
`

type UpdateEngagementUpdateParams struct {
	Status         string
	Content        string
	EventDate      time.Time
	DeliberationID *uuid.UUID
	ExternalSource *string
	ID             uuid.UUID
}

func (q *Queries) UpdateEngagementUpdate(ctx context.Context, arg UpdateEngagementUpdateParams) (AppEngagementUpdate, error) {
	row := q.db.QueryRow(ctx, updateEngagementUpdate,
		arg.Status,
		arg.Content,
		arg.EventDate,
		arg.DeliberationID,
		arg.ExternalSource,
		arg.ID,
	)
	var i AppEngagementUpdate
	err := row.Scan(
		&i.ID,
		&i.EngagementID,
		&i.Status,
		&i.Content,
		&i.EventDate,
		&i.DeliberationID,
		&i.ExternalSource,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
