// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: indicateurs.sql

package dao

import (
	"context"
	"time"
)

const listIndicateurObservationsByKey = `-- name: ListIndicateurObservationsByKey :many
SELECT id, key, reference, data, created_at, updated_at FROM app.indicateur_observations
WHERE key = $1
ORDER BY reference ASC
`

// Renvoie toutes les observations d'un indicateur, triées par reference
// ascendante (= ordre chronologique si la convention de naming est respectée).
func (q *Queries) ListIndicateurObservationsByKey(ctx context.Context, key string) ([]AppIndicateurObservation, error) {
	rows, err := q.db.Query(ctx, listIndicateurObservationsByKey, key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppIndicateurObservation
	for rows.Next() {
		var i AppIndicateurObservation
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Reference,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIndicateurs = `-- name: ListIndicateurs :many
SELECT
    key,
    COUNT(*)::bigint                   AS observations_count,
    MAX(reference)::text               AS last_reference,
    MIN(reference)::text               AS first_reference,
    MAX(updated_at)::timestamptz       AS last_updated_at
FROM app.indicateur_observations
GROUP BY key
ORDER BY key
`

type ListIndicateursRow struct {
	Key               string
	ObservationsCount int64
	LastReference     string
	FirstReference    string
	LastUpdatedAt     time.Time
}

// Renvoie une ligne par `key` avec ses métadonnées agrégées.
// `last_reference` est la reference lexicographiquement max — convention :
// tout calculator doit produire des references triables (YYYY, YYYY-MM,
// YYYY-MM-DD, ou un timestamp ISO).
func (q *Queries) ListIndicateurs(ctx context.Context) ([]ListIndicateursRow, error) {
	rows, err := q.db.Query(ctx, listIndicateurs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIndicateursRow
	for rows.Next() {
		var i ListIndicateursRow
		if err := rows.Scan(
			&i.Key,
			&i.ObservationsCount,
			&i.LastReference,
			&i.FirstReference,
			&i.LastUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
