// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dao

import (
	"time"

	"github.com/google/uuid"
)

type AppDeliberation struct {
	ID               uuid.UUID
	DelibID          string
	Collectivite     string
	Instance         string
	CollNom          string
	CollSiret        string
	DelibDate        time.Time
	DelibObjet       string
	DelibMatiereCode string
	DelibMatiereNom  string
	PrefID           *string
	PrefDate         *time.Time
	VoteEffectif     int32
	VoteReel         int32
	VotePour         int32
	VoteContre       int32
	VoteAbstention   int32
	RawData          []byte
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Documents        []byte
}

type AppIndicateurObservation struct {
	ID        uuid.UUID
	Key       string
	Reference string
	Data      []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AppPasswordResetToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Hash      string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type AppRefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Hash      string
	ExpiresAt time.Time
	CreatedAt time.Time
	DeletedAt *time.Time
}

type AppUser struct {
	ID        uuid.UUID
	Email     string
	Password  string
	Roles     []string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}
