// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset_tokens.sql

package dao

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO app.password_reset_tokens (user_id, hash, expires_at)
VALUES ($1, $2, $3)
`

type CreatePasswordResetTokenParams struct {
	UserID    uuid.UUID
	Hash      string
	ExpiresAt time.Time
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, createPasswordResetToken, arg.UserID, arg.Hash, arg.ExpiresAt)
	return err
}

const deletePasswordResetTokensByUserID = `-- name: DeletePasswordResetTokensByUserID :exec
DELETE FROM app.password_reset_tokens
WHERE user_id = $1
`

func (q *Queries) DeletePasswordResetTokensByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePasswordResetTokensByUserID, userID)
	return err
}

const findPasswordResetTokenByHashForUpdate = `-- name: FindPasswordResetTokenByHashForUpdate :one
SELECT id, user_id, hash, expires_at, created_at FROM app.password_reset_tokens
WHERE hash = $1
FOR UPDATE
`

func (q *Queries) FindPasswordResetTokenByHashForUpdate(ctx context.Context, hash string) (AppPasswordResetToken, error) {
	row := q.db.QueryRow(ctx, findPasswordResetTokenByHashForUpdate, hash)
	var i AppPasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
