// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package dao

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO app.refresh_tokens(user_id, hash, expires_at) 
VALUES ($1, $2, $3)
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID
	Hash      string
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken, arg.UserID, arg.Hash, arg.ExpiresAt)
	return err
}

const deleteRefreshTokenByHash = `-- name: DeleteRefreshTokenByHash :exec
UPDATE app.refresh_tokens
SET deleted_at = NOW()
WHERE hash = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteRefreshTokenByHash(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenByHash, hash)
	return err
}

const deleteRefreshTokensByUserID = `-- name: DeleteRefreshTokensByUserID :exec
UPDATE app.refresh_tokens
SET deleted_at = NOW()
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteRefreshTokensByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokensByUserID, userID)
	return err
}

const findRefreshTokenByHashForUpdate = `-- name: FindRefreshTokenByHashForUpdate :one
SELECT id, user_id, hash, expires_at, created_at, deleted_at FROM app.refresh_tokens
WHERE hash = $1
FOR UPDATE
`

func (q *Queries) FindRefreshTokenByHashForUpdate(ctx context.Context, hash string) (AppRefreshToken, error) {
	row := q.db.QueryRow(ctx, findRefreshTokenByHashForUpdate, hash)
	var i AppRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
