// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dao

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO app.users(email, password, roles)
VALUES ($1, $2, $3)
`

type CreateUserParams struct {
	Email    string
	Password string
	Roles    []string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.Email, arg.Password, arg.Roles)
	return err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, password, roles, created_at, updated_at, deleted_at FROM app.users
WHERE email = $1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (AppUser, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Roles,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, email, password, roles, created_at, updated_at, deleted_at FROM app.users
WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id uuid.UUID) (AppUser, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Roles,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE app.users
SET password = $2
WHERE id = $1
RETURNING id
`

type UpdateUserPasswordParams struct {
	ID       uuid.UUID
	Password string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.Password)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const userExistsByEmail = `-- name: UserExistsByEmail :one
SELECT EXISTS(
    SELECT 1 FROM app.users
    WHERE email = $1
) AS exists
`

func (q *Queries) UserExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
