/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PasswordResetRouteImport } from './routes/password-reset'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NominationsIndexRouteImport } from './routes/nominations/index'
import { Route as IndicateursIndexRouteImport } from './routes/indicateurs/index'
import { Route as EspaceContributeurIndexRouteImport } from './routes/espace-contributeur/index'
import { Route as EngagementsIndexRouteImport } from './routes/engagements/index'
import { Route as DeliberationsIndexRouteImport } from './routes/deliberations/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as IndicateursIndicateurKeyRouteImport } from './routes/indicateurs/$indicateurKey'
import { Route as EngagementsEngagementIdRouteImport } from './routes/engagements/$engagementId'
import { Route as DeliberationsDeliberationIdRouteImport } from './routes/deliberations/$deliberationId'
import { Route as AdminInviterContributeurRouteImport } from './routes/admin/inviter-contributeur'
import { Route as EspaceContributeurEngagementsNouveauRouteImport } from './routes/espace-contributeur/engagements/nouveau'

const MentionsLegalesLazyRouteImport = createFileRoute('/mentions-legales')()

const MentionsLegalesLazyRoute = MentionsLegalesLazyRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/mentions-legales.lazy').then((d) => d.Route),
)
const PasswordResetRoute = PasswordResetRouteImport.update({
  id: '/password-reset',
  path: '/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NominationsIndexRoute = NominationsIndexRouteImport.update({
  id: '/nominations/',
  path: '/nominations/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicateursIndexRoute = IndicateursIndexRouteImport.update({
  id: '/indicateurs/',
  path: '/indicateurs/',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceContributeurIndexRoute = EspaceContributeurIndexRouteImport.update({
  id: '/espace-contributeur/',
  path: '/espace-contributeur/',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementsIndexRoute = EngagementsIndexRouteImport.update({
  id: '/engagements/',
  path: '/engagements/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliberationsIndexRoute = DeliberationsIndexRouteImport.update({
  id: '/deliberations/',
  path: '/deliberations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicateursIndicateurKeyRoute =
  IndicateursIndicateurKeyRouteImport.update({
    id: '/indicateurs/$indicateurKey',
    path: '/indicateurs/$indicateurKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const EngagementsEngagementIdRoute = EngagementsEngagementIdRouteImport.update({
  id: '/engagements/$engagementId',
  path: '/engagements/$engagementId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliberationsDeliberationIdRoute =
  DeliberationsDeliberationIdRouteImport.update({
    id: '/deliberations/$deliberationId',
    path: '/deliberations/$deliberationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminInviterContributeurRoute =
  AdminInviterContributeurRouteImport.update({
    id: '/admin/inviter-contributeur',
    path: '/admin/inviter-contributeur',
    getParentRoute: () => rootRouteImport,
  } as any)
const EspaceContributeurEngagementsNouveauRoute =
  EspaceContributeurEngagementsNouveauRouteImport.update({
    id: '/espace-contributeur/engagements/nouveau',
    path: '/espace-contributeur/engagements/nouveau',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/password-reset': typeof PasswordResetRoute
  '/mentions-legales': typeof MentionsLegalesLazyRoute
  '/admin/inviter-contributeur': typeof AdminInviterContributeurRoute
  '/deliberations/$deliberationId': typeof DeliberationsDeliberationIdRoute
  '/engagements/$engagementId': typeof EngagementsEngagementIdRoute
  '/indicateurs/$indicateurKey': typeof IndicateursIndicateurKeyRoute
  '/admin/': typeof AdminIndexRoute
  '/deliberations/': typeof DeliberationsIndexRoute
  '/engagements/': typeof EngagementsIndexRoute
  '/espace-contributeur/': typeof EspaceContributeurIndexRoute
  '/indicateurs/': typeof IndicateursIndexRoute
  '/nominations/': typeof NominationsIndexRoute
  '/espace-contributeur/engagements/nouveau': typeof EspaceContributeurEngagementsNouveauRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/password-reset': typeof PasswordResetRoute
  '/mentions-legales': typeof MentionsLegalesLazyRoute
  '/admin/inviter-contributeur': typeof AdminInviterContributeurRoute
  '/deliberations/$deliberationId': typeof DeliberationsDeliberationIdRoute
  '/engagements/$engagementId': typeof EngagementsEngagementIdRoute
  '/indicateurs/$indicateurKey': typeof IndicateursIndicateurKeyRoute
  '/admin': typeof AdminIndexRoute
  '/deliberations': typeof DeliberationsIndexRoute
  '/engagements': typeof EngagementsIndexRoute
  '/espace-contributeur': typeof EspaceContributeurIndexRoute
  '/indicateurs': typeof IndicateursIndexRoute
  '/nominations': typeof NominationsIndexRoute
  '/espace-contributeur/engagements/nouveau': typeof EspaceContributeurEngagementsNouveauRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/password-reset': typeof PasswordResetRoute
  '/mentions-legales': typeof MentionsLegalesLazyRoute
  '/admin/inviter-contributeur': typeof AdminInviterContributeurRoute
  '/deliberations/$deliberationId': typeof DeliberationsDeliberationIdRoute
  '/engagements/$engagementId': typeof EngagementsEngagementIdRoute
  '/indicateurs/$indicateurKey': typeof IndicateursIndicateurKeyRoute
  '/admin/': typeof AdminIndexRoute
  '/deliberations/': typeof DeliberationsIndexRoute
  '/engagements/': typeof EngagementsIndexRoute
  '/espace-contributeur/': typeof EspaceContributeurIndexRoute
  '/indicateurs/': typeof IndicateursIndexRoute
  '/nominations/': typeof NominationsIndexRoute
  '/espace-contributeur/engagements/nouveau': typeof EspaceContributeurEngagementsNouveauRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/inscription'
    | '/login'
    | '/password-reset'
    | '/mentions-legales'
    | '/admin/inviter-contributeur'
    | '/deliberations/$deliberationId'
    | '/engagements/$engagementId'
    | '/indicateurs/$indicateurKey'
    | '/admin/'
    | '/deliberations/'
    | '/engagements/'
    | '/espace-contributeur/'
    | '/indicateurs/'
    | '/nominations/'
    | '/espace-contributeur/engagements/nouveau'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/inscription'
    | '/login'
    | '/password-reset'
    | '/mentions-legales'
    | '/admin/inviter-contributeur'
    | '/deliberations/$deliberationId'
    | '/engagements/$engagementId'
    | '/indicateurs/$indicateurKey'
    | '/admin'
    | '/deliberations'
    | '/engagements'
    | '/espace-contributeur'
    | '/indicateurs'
    | '/nominations'
    | '/espace-contributeur/engagements/nouveau'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/inscription'
    | '/login'
    | '/password-reset'
    | '/mentions-legales'
    | '/admin/inviter-contributeur'
    | '/deliberations/$deliberationId'
    | '/engagements/$engagementId'
    | '/indicateurs/$indicateurKey'
    | '/admin/'
    | '/deliberations/'
    | '/engagements/'
    | '/espace-contributeur/'
    | '/indicateurs/'
    | '/nominations/'
    | '/espace-contributeur/engagements/nouveau'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  InscriptionRoute: typeof InscriptionRoute
  LoginRoute: typeof LoginRoute
  PasswordResetRoute: typeof PasswordResetRoute
  MentionsLegalesLazyRoute: typeof MentionsLegalesLazyRoute
  AdminInviterContributeurRoute: typeof AdminInviterContributeurRoute
  DeliberationsDeliberationIdRoute: typeof DeliberationsDeliberationIdRoute
  EngagementsEngagementIdRoute: typeof EngagementsEngagementIdRoute
  IndicateursIndicateurKeyRoute: typeof IndicateursIndicateurKeyRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DeliberationsIndexRoute: typeof DeliberationsIndexRoute
  EngagementsIndexRoute: typeof EngagementsIndexRoute
  EspaceContributeurIndexRoute: typeof EspaceContributeurIndexRoute
  IndicateursIndexRoute: typeof IndicateursIndexRoute
  NominationsIndexRoute: typeof NominationsIndexRoute
  EspaceContributeurEngagementsNouveauRoute: typeof EspaceContributeurEngagementsNouveauRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset': {
      id: '/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof PasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nominations/': {
      id: '/nominations/'
      path: '/nominations'
      fullPath: '/nominations/'
      preLoaderRoute: typeof NominationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicateurs/': {
      id: '/indicateurs/'
      path: '/indicateurs'
      fullPath: '/indicateurs/'
      preLoaderRoute: typeof IndicateursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace-contributeur/': {
      id: '/espace-contributeur/'
      path: '/espace-contributeur'
      fullPath: '/espace-contributeur/'
      preLoaderRoute: typeof EspaceContributeurIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagements/': {
      id: '/engagements/'
      path: '/engagements'
      fullPath: '/engagements/'
      preLoaderRoute: typeof EngagementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliberations/': {
      id: '/deliberations/'
      path: '/deliberations'
      fullPath: '/deliberations/'
      preLoaderRoute: typeof DeliberationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicateurs/$indicateurKey': {
      id: '/indicateurs/$indicateurKey'
      path: '/indicateurs/$indicateurKey'
      fullPath: '/indicateurs/$indicateurKey'
      preLoaderRoute: typeof IndicateursIndicateurKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagements/$engagementId': {
      id: '/engagements/$engagementId'
      path: '/engagements/$engagementId'
      fullPath: '/engagements/$engagementId'
      preLoaderRoute: typeof EngagementsEngagementIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliberations/$deliberationId': {
      id: '/deliberations/$deliberationId'
      path: '/deliberations/$deliberationId'
      fullPath: '/deliberations/$deliberationId'
      preLoaderRoute: typeof DeliberationsDeliberationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inviter-contributeur': {
      id: '/admin/inviter-contributeur'
      path: '/admin/inviter-contributeur'
      fullPath: '/admin/inviter-contributeur'
      preLoaderRoute: typeof AdminInviterContributeurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace-contributeur/engagements/nouveau': {
      id: '/espace-contributeur/engagements/nouveau'
      path: '/espace-contributeur/engagements/nouveau'
      fullPath: '/espace-contributeur/engagements/nouveau'
      preLoaderRoute: typeof EspaceContributeurEngagementsNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  InscriptionRoute: InscriptionRoute,
  LoginRoute: LoginRoute,
  PasswordResetRoute: PasswordResetRoute,
  MentionsLegalesLazyRoute: MentionsLegalesLazyRoute,
  AdminInviterContributeurRoute: AdminInviterContributeurRoute,
  DeliberationsDeliberationIdRoute: DeliberationsDeliberationIdRoute,
  EngagementsEngagementIdRoute: EngagementsEngagementIdRoute,
  IndicateursIndicateurKeyRoute: IndicateursIndicateurKeyRoute,
  AdminIndexRoute: AdminIndexRoute,
  DeliberationsIndexRoute: DeliberationsIndexRoute,
  EngagementsIndexRoute: EngagementsIndexRoute,
  EspaceContributeurIndexRoute: EspaceContributeurIndexRoute,
  IndicateursIndexRoute: IndicateursIndexRoute,
  NominationsIndexRoute: NominationsIndexRoute,
  EspaceContributeurEngagementsNouveauRoute:
    EspaceContributeurEngagementsNouveauRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
