# Utiliser l'image officielle PostgreSQL
FROM postgres:17

# Copier le fichier d'initialisation SQL dans le répertoire d'initialisation de PostgreSQL
# COPY schema.sql /docker-entrypoint-initdb.d/

# Exposer le port PostgreSQL par défaut
EXPOSE 5432